signal_name: MILITARY_ACTIONS_SIGNAL
description: "Military Conflict Prediction Signal - Keywords: military, strike, invasion, war, engage, clash"
input_manifest_files:
  - "polymarket_data/_manifest_geopolitics__foreign_policy_comprehensive.csv"
  - "polymarket_data/_manifest_geopolitics__war.csv"
  - "polymarket_data/_manifest_custom_world_affairs.csv"
output_file: "sector_signals/military_actions_signal.csv"
generator_type: "vwp"
min_quality_score: 15
polarity_rules:
  concept_description: "Military Conflict & Escalation Risk"
  increase_uncertainty: # Keywords assigned +1 polarity (military escalation)
    - "military.*action"
    - "military.*strike"
    - "invade"
    - "strike.*on"
    - "attack.*on"
    - "attack.*by"
    - "strike.*by"
    - "military.*engagement"
    - "military.*clash"
    - "military.*response"
    - "declare.*war"
    - "military.*airstrike"
    - "invasion"
    - "capture.*by"
    - "seize.*by"
    - "escalat"
    - "coalition.*strike"
    - "air.*raid"
    - "bombard"
    - "bombed"
    - "missile.*strike"
    - "missile.*attack"
    - "rocket.*strike"
    - "rocket.*attack"
    - "dron.*strike"
    - "drone.*attack"
    - "artillery.*strike"
    - "shelling"
    - "troop.*deployment"
    - "troop.*movement"
    - "offensive"
    - "counterattack"
    - "counter.*strike"
    - "ground.*offensive"
    - "naval.*blockade"
    - "siege"
    - "incursion"
    - "raid"
    - "ambush"
    - "assault"
    - "hostile.*action"
    - "military.*intervention"
    - "occupy"
    - "territorial.*expansion"
    - "annex"
    - "take.*control"
    - "seizure"
    - "hostilities.*begin"
    - "conflict.*escalates"
    - "military.*build.*up"
  decrease_uncertainty: # Keywords assigned -1 polarity (de-escalation/stability)
    - "ceasefire"
    - "peace.*deal"
    - "withdraw.*from"
    - "pull.*out"
    - "end.*military"
    - "end.*hostilities"
    - "no.*more.*attacks"
    - "nuclear.*freeze"
    - "disarmament"
    - "stabilize.*military"
    - "reduce.*forces"
    - "peace.*agreement"
    - "truce"
    - "armistice"
    - "stand.*down"
    - "troop.*withdrawal"
    - "de.*escalation"
    - "military.*stand.*down"
    - "no.*further.*action"
    - "conflict.*resolution"
    - "hostilities.*cease"
    - "peace.*talks"
    - "diplomatic.*solution"
    - "no.*military.*response"
    - "cool.*down.*period"
    - "defuse.*tension"
  market_polarity_overrides:
    # Any market-specific polarity adjustments can be added here
    # Example format:
    # "specific-market-slug": -1
