signal_name: US_GDP
description: "Expected GDP Growth Signal - Volume Weighted Expected Value from GDP Markets"
input_manifest_files:
  - "polymarket_data/_manifest_gdp.csv"
output_file: "signal_vwev_gdp.csv"
generator_type: "unified"

# Event grouping and rolling configuration
event_grouping_pattern: "US GDP growth in Q(\\d) (\\d{4})"
roll_on_field: "volume"
open_bin_handling_method: "fit_pareto"

# Signal generation parameters
min_quality_score: 20
lookback_days: 180

# Expected value calculation parameters
distribution_bins:
  percentiles: [0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]

# Analysis configuration - use signal changes, not levels
use_signal_changes: true

polarity_rules:
  concept_description: "US GDP Growth Expectation Change"
  positive_growth: # Keywords indicating positive growth
    - "greater than"
    - "more than"
    - "above"
    - "grow.*by"
    - "increase.*by"
    - "exceed"
    - "reach.*more.*than"
  negative_growth: # Keywords indicating negative/lower growth
    - "less than"
    - "below"
    - "lower.*than"
    - "decrease.*by"
    - "decline.*by"
    - "fall.*by"
    - "contraction"
  market_polarity_overrides:
    # Manual polarity overrides for GDP-specific markets
