signal_name: US_INFLATION_MONTHLY
description: "Monthly Inflation Change Expectations - Volume Weighted Expected Value from CPI Threshold Markets"
input_manifest_files:
  - "polymarket_data/manifest/_manifest_inflation.csv"
output_file: "data/processed_signals/signal_vwev_inflation_monthly.csv"

# Event grouping for monthly forecasts - groups by month/period
event_grouping_pattern: "monthly.*by.*in\\s+(\\w+)$"  # Matches "in September", "in October", etc.
generator_type: "vwev_rolled"

# Event grouping for monthly forecasts - groups by month/period
event_grouping_pattern: "in\\s+(\\w+)$"  # Matches month names (January, September, etc.)
roll_on_field: "volume"
open_bin_handling_method: "fit_pareto"

# Signal generation parameters
min_quality_score: 20
lookback_days: 180

# Expected value calculation parameters
distribution_bins:
  percentiles: [0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]

# Analysis configuration - use signal changes, not levels
use_signal_changes: true

polarity_rules:
  concept_description: "Monthly Inflation Change"
  increase_inflation: # Keywords indicating rising short-term inflation
    - "increase.*by"
    - "rise.*by"
    - "grow.*by"
    - "higher.*than"
    - "exceed"
  decrease_inflation: # Keywords indicating falling short-term inflation
    - "decrease.*by"
    - "fall.*by"
    - "lower.*than"
    - "below"
    - "less.*than"
  market_polarity_overrides:
    # Manual polarity overrides can be added here if needed
